image: archlinux
packages:
  - meson
  - wayland
  - wayland-protocols
  - pixman
  - libpng
  - libjpeg-turbo
sources:
  - https://github.com/emerison/grim
tasks:
  - setup: |
      cd grim
      meson build
  - build: |
      cd grim
      ninja -C build
